export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  CODE_REVIEW = 'CODE_REVIEW',
  READY_FOR_TESTING = 'READY_FOR_TESTING',
  TESTING = 'TESTING',
  DONE = 'DONE',
  DEPRECATED = 'DEPRECATED'
}
